// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package authors

import (
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entery struct {
	ID        int64
	AccountID int64
	// can be negative or positive
	Amout     int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// it must be positive
	Amout     int64
	CreatedAt time.Time
}
